### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by Givoric** [LambdAurora/LambdaBetterGrass#37]
After i launch minecraft this happens:
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "dev.lambdaurora.lambdabettergrass.LambdaBetterGrass.log(String)" because "mod" is null

This is the crash log: https://pastebin.com/RFbA1U4a
Also it seems to happen since i added requiem to my modpack

**Comment by CactusDuud** [comment]
I've gotten the same crash without Requiem.

**Comment by Givoric** [comment]
weird since to me it happens only after installing requiem

**Comment by kawalain** [comment]
Same error here but no requiem

Edit:
Nevermind, it caused by `architectury-3.4.9.jar` which is depends of `RoughlyEnoughItems-7.1.390.jar`

```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 1/23/22, 4:14 PM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "dev.lambdaurora.lambdabettergrass.LambdaBetterGrass.log(String)" because "mod" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.17)
	at net.minecraft.resource.ReloadableResourceManagerImpl.handler$bhf000$onReload(ReloadableResourceManagerImpl:3043)
	at net.minecraft.resource.ReloadableResourceManagerImpl.reload(ReloadableResourceManagerImpl:137)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:623)
	at net.minecraft.client.main.Main.main(Main:199)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_3304.handler$bhf000$onReload(class_3304.java:3043)
	at net.minecraft.class_3304.method_18232(class_3304.java:137)
	at net.minecraft.class_310.<init>(class_310.java:623)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.16.2-zen1-1-zen
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 425277424 bytes (405 MiB) / 1006632960 bytes (960 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700U with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Lucienne
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x164c
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 32295.57
	Virtual memory used (MB): 3775.61
	Swap memory total (MB): 24576.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.1
		architectury: Architectury 3.4.9
		authme: Auth Me 2.2.0
		autoswitch: AutoSwitch 3.5.0
		autoswitch-api: AutoSwitch API 1.0.0
		betterf3: BetterF3 1.2.2
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_yaml: yaml 3.6.5
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.13.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.13.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.13.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		com_github_reviversmc_modget-lib: modget-lib 3.0.0
		com_github_reviversmc_modget-manifest-api_compat: compat 0.2.1
		com_github_reviversmc_modget-manifest-api_spec3: spec3 0.2.1
		com_github_reviversmc_modget-manifest-api_spec4: spec4 0.2.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		continuity: Continuity 1.0.3+1.18
		cosmetica: Cosmetica 0.3.2
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		dashloader: DashLoader 3.0-rc14-1.18
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.1
		dev_quantumfusion_hyphen: hyphen 0.1
		dynamicfps: Dynamic FPS 2.1.0
		easiercrafting: EasierCrafting 1.18.1-fabric0.45.0-1.7
		eatinganimationid: Eating Animation 1.2
		entityculling: EntityCulling-Fabric 1.3.3
		equipmentcompare: Equipment Compare 1.2.11
		extrasounds: Extra Sounds 2.2.0+1.18
		fabric: Fabric API 0.46.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.10+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.13+b0b66fc365
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+13eda06565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.0+0a73a6c265
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		farsight: Farsight Mod 1.18-1.5
		gbfabrictools: GBfabrictools 1.3.4+1.18
		goosik-config: goosik-config 0.2.0
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.2
		indium: Indium 1.0.2-alpha2+mc1.18.1
		inspecio: Inspecio 1.2.1+1.18
		inventoryhud: Inventory HUD + 3.4.2
		io_airlift_aircompressor: aircompressor 0.21
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0-beta.2
		krypton: Krypton 0.1.6
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.6
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		modget: Modget 0.4.3+1.17
		modget-core: Modget Core 0.4.3
		modmenu: Mod Menu 3.0.1
		multiconnect: MultiConnect 1.5.10
		multiconnect-api: MultiConnect API 1.5.10
		namepain: Name Pain 1.4.0
		notenoughanimations: NotEnoughAnimations 1.4.0
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		org_aeonbits_owner_owner: owner 1.0.12
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-text: commons-text 1.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_yaml_snakeyaml: snakeyaml 1.29
		physicsmod: Physics Mod 2.6.5
		pinglist: PingList 1.3.3
		presencefootsteps: Presence Footsteps 1.4.0
		pride: Pride Lib 1.1.0+1.17
		reeses-sodium-options: Reese's Sodium Options 1.2.4
		roughlyenoughitems: Roughly Enough Items 7.1.390
		skinlayers: 3d Skin Layers 1.3.1
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.3.8
		soundcategories: Sound Categories 1.2.0+1.18
		soundphysics: Sound Physics 0.5.2
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		visuality: Visuality 0.4.0
		visualoverhaul: VisualOverhaul 4.0.0
		worldedit: WorldEdit 7.2.8+6008-1246d61
		wthit: wthit 4.4.1
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD RENOIR (DRM 3.44.0, 5.16.2-zen1-1-zen, LLVM 13.0.0) GL version 4.6 (Core Profile) Mesa 21.3.4, AMD
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 16x AMD Ryzen 7 5700U with Radeon Graphics
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader)
```

**Comment by tennox** [comment]
For me it was a mod depending on Trinkets API which I forgot
(the mod was travellers backpack)
