### ISSUE TITLE
Create's Worldshaper causes crash when it selects grass.

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [LambdAurora/LambdaBetterGrass#67]
It seems LambdaBetterGrass causes the crash when Create tries to get a block model for the worldshaper.
![image](https://user-images.githubusercontent.com/65097669/204103780-bc2df9ba-fa16-45d5-bde0-60eaa8b281f6.png)
![image](https://user-images.githubusercontent.com/65097669/204103783-2e812a47-3d2e-46c4-9b56-a7cbca909db2.png)

**Comment by rapus95** [comment]
```
[17:38:16] [Render thread/INFO]: Stopping worker threads
[17:38:16] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering item
	at net.minecraft.class_918.method_4026(class_918.java:360) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_36543(class_918.java:340) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_27951(class_918.java:336) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1762(class_329.java:1257) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1759(class_329.java:579) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:204) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:862) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.7.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.7.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.UnsupportedOperationException: LambdaBetterGrass models should never try to render as an item!
	at dev.lambdaurora.lambdabettergrass.model.LBGBakedModel.emitItemQuads(LBGBakedModel.java:167) ~[lambdabettergrass-1.3.0+1.19.jar:?]
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:111) ~[indium-1.0.9+mc1.19.2.jar:?]
	at net.minecraft.class_918.handler$bgm000$hook_renderItem(class_918.java:1057) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_23179(class_918.java:132) ~[client-intermediary.jar:?]
	at com.simibubi.create.content.curiosities.zapper.ZapperItemRenderer.renderBlockUsed(ZapperItemRenderer.java:48) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.curiosities.zapper.ZapperItemRenderer.render(ZapperItemRenderer.java:27) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.curiosities.zapper.terrainzapper.WorldshaperItemRenderer.render(WorldshaperItemRenderer.java:26) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.content.curiosities.zapper.terrainzapper.WorldshaperItemRenderer.render(WorldshaperItemRenderer.java:21) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.foundation.item.render.CustomRenderedItemModelRenderer.render(CustomRenderedItemModelRenderer.java:27) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at net.minecraft.class_756.handler$bfl000$fabric_onRender(class_756.java:540) ~[client-intermediary.jar:?]
	at net.minecraft.class_756.method_3166(class_756.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_23179(class_918.java:133) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4021(class_918.java:307) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4026(class_918.java:350) ~[client-intermediary.jar:?]
	... 25 more
```

**Comment by Sultansmooth** [comment]
noticed this issue today as well

**Comment by NONPLAYT** [comment]
same issue as well
